### PR TITLE
addpatch: fuse2

### PR DESCRIPTION
**Pull request by leavelet**

### CODE REVIEW

**Review by wszqkzqk — CHANGES_REQUESTED** [review]
Do not put `config.guess` and `config.sub` in the patch dir.

Please read [loong tools design](https://wszqkzqk.github.io/2024/08/12/loong-tools-design/#%E7%89%B9%E6%AE%8A%E6%83%85%E5%86%B5) and [example of updating `config.guess` with other changes](https://github.com/lcpu-club/loongarch-packages/blob/master/gimp/loong.patch#L9)

**Comment by wszqkzqk** [comment]
Also please add your detailed description in [commit message](https://github.com/lcpu-club/loongarch-packages?tab=readme-ov-file#%E6%8F%90%E4%BA%A4-pr-%E7%9A%84%E4%B8%80%E4%BA%9B%E6%A0%BC%E5%BC%8F%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

**Comment by setarcos** [comment]
fuse2 has already packed in extra-testing. Beside config.guess, why fuse_loop_mt.c needs changing the position of include files?

**Comment by leavelet** [comment]
> fuse2 has already packed in extra-testing. Beside config.guess, why fuse_loop_mt.c needs changing the position of include files?

To detect size of numbers correctly

**Pull request closed without merging**
